version: 0.2

phases:
  pre_build:
    commands:
      - python3 -m venv ~/.venv
      - source ~/.venv/bin/activate
      - make install
      - make lint

  build:
    commands:
      - make deploy

eb_codebuild_settings:
  CodeBuildServiceRole: CodeBuildServiceRole
  ComputeType: BUILD_GENERAL1_SMALL
  Image: "aws/codebuild/amazonlinux2-aarch64-standard:2.0"
  Timeout: 40
